### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by JStika** [saleemkce/tos_dump#1]
I cannot download ziped sql dump.

**Comment by saleemkce** [comment]
No, it's downloadable here: For php, https://github.com/saleemkce/tos_dump/blob/master/php and for nodeJs, https://github.com/saleemkce/tos_dump/tree/master/nodejs   (https://github.com/saleemkce/tos_dump/blob/master/nodejs/tosdata.zip)  May be try from another browser?

**Comment by JStika** [comment]
Thank you for your answer.
