### ISSUE TITLE
Licence Key

### ISSUE THREAD

**Issue by JStika** [saleemkce/tos_dump#2]
How can I to use minified version if I buy Licence Key?

**Comment by saleemkce** [comment]
You have to upload the minified version in your site assets folder and map it; something like,

`<script src="assets/js/timeonsitetracker.min.js"></script>`

Generally speaking, even in minified version,  the blocks starting and ending like,

```
/**@preserve
*/
```
should be intact. This is where you need to update the licence key. The current version can be seen here https://github.com/saleemkce/timeonsite/blob/master/timeonsitetracker.min.js where comment blocks are intact.

**Comment by JStika** [comment]
Thank you for your answer.

**Comment by saleemkce** [comment]
@JStika I'm glad it answered your question.
